name: Release to Production

permissions:
  contents: write

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  build:
    name: Build and Release
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
        with:
          ref: master

      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '18'
          distribution: 'oracle'

      - name: Cache Gradle packages
        uses: actions/cache@v3
        with:
          path: |
            ~/.gradle/caches
            ~/.gradle/wrapper
          key: gradle-${{ runner.os }}-${{ hashFiles('**/*.gradle*', '**/gradle-wrapper.properties') }}
          restore-keys: |
            gradle-${{ runner.os }}

      - name: Build with Gradle
        run: ./gradlew build

      - name: Get version from Gradle file
        id: get_version
        run: |
          VERSION=$(grep 'version =' build.gradle.kts | awk -F'"' '{print $2}')
          echo "VERSION=$VERSION" >> $GITHUB_ENV

      - name: Create tag and release
        run: |
          git fetch --all
          git checkout master 
          git tag ${{ env.VERSION }}
          git push origin ${{ env.VERSION }}

      - name: Create GitHub release
        uses: actions/create-release@v1
        with:
          tag_name: ${{ env.VERSION }}
          release_name: V${{ env.VERSION }}
          body: Automated release generated by GitHub Actions.
          draft: false
          prerelease: false
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Publish to JitPack
        run: ./gradlew publish